Fixes #26 - Add aarch64 profile and Docker files
netty/netty-incubator-transport-io_uring pull request #27
Opened 2020-12-08 09:29 UTC by martin-g

2020-12-08 09:29 UTC, martin-g commented
At the moment it fails with:
```
cross-compile-aarch64-build_1          | [INFO] ------------------------------------------------------------------------
cross-compile-aarch64-build_1          | [INFO] BUILD FAILURE
cross-compile-aarch64-build_1          | [INFO] ------------------------------------------------------------------------
cross-compile-aarch64-build_1          | [INFO] Total time:  5.946 s
cross-compile-aarch64-build_1          | [INFO] Finished at: 2020-12-08T09:20:50Z
cross-compile-aarch64-build_1          | [INFO] ------------------------------------------------------------------------
cross-compile-aarch64-build_1          | [ERROR] Failed to execute goal on project netty-incubator-transport-native-io_uring: Could not resolve dependencies for project io.netty.incubator:netty-incubator-transport-native-io_uring:jar:0.0.3.Final-SNAPSHOT: Could not find artifact io.netty:netty-transport-native-unix-common:jar:linux-aarch_64:0.0.3.Final-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
cross-compile-aarch64-build_1          | [ERROR] 
```
because of #22

2020-12-08 09:40 UTC, normanmaurer commented
@martin-g can you sign our ICLA:

https://netty.io/s/icla ?

2020-12-08 09:43 UTC, martin-g commented
Done!

2020-12-08 09:57 UTC, normanmaurer requested changes

2020-12-08 09:57 UTC, normanmaurer commented on pom.xml
> +                  <name>netty_transport_native_epoll_aarch_64</name>
```suggestion
                  <name>netty_quiche_linux_aarch_64</name>
```

2020-12-08 09:57 UTC, normanmaurer commented on pom.xml
> +                      <Bundle-NativeCode>META-INF/native/libnetty_transport_native_epoll_aarch_64.so; osname=Linux; processor=aarch_64,*</Bundle-NativeCode>
```suggestion
                      <Bundle-NativeCode>META-INF/native/libnetty_quiche_linux_aarch_64.so; osname=Linux; processor=aarch_64,*</Bundle-NativeCode>
```

2020-12-08 15:43 UTC, martin-g commented
I've just noticed https://github.com/netty/netty/pull/10845
Let me update to 4.1.55 and see how it goes!

2020-12-08 16:22 UTC, martin-g commented
@normanmaurer All should be good now!

2020-12-09 10:06 UTC, normanmaurer commented
There were still a few small issues... I fixed these and opened https://github.com/netty/netty-incubator-transport-io_uring/pull/29.

2020-12-09 10:06 UTC, closed without merging