Using a shared linux worker queue
netty/netty-incubator-transport-io_uring pull request #30
Opened 2020-12-09 17:42 UTC by 1Jo1

Motivation:

on each eventloop 4 kthread worker will be created, to use the wq more efficiently you can attach different ringbuffers( (eventloops) to the same wq(worker queue)

Modifications:

- attach the wqFd to the ring buffer

Result:

using less worker queues

2020-12-10 07:08 UTC, martin-g commented on src/main/java/io/netty/incubator/channel/uring/Native.java
> +    //the number of eventLoop which are associated to one work queue
s/eventLoop/eventLoops/

2020-12-10 09:14 UTC, normanmaurer commented
@1Jo1 you have any benchmarks to share here ?

2020-12-10 09:49 UTC, normanmaurer requested changes

2020-12-10 09:49 UTC, normanmaurer commented on src/main/c/netty_io_uring_native.c
> +    if (wqFd > 0) {
should we better use > -1 and use -1 if we don't want to use a wqFd. ?

2020-12-10 09:49 UTC, normanmaurer commented on src/main/c/netty_io_uring_native.c
> +    if (wqFd > 0) {
Actually it seems like we use -1 in the java code already. So I think just this if branch should be changed

2020-12-11 16:07 UTC, 1Jo1 commented
yeah sure i’m gonna do it later

2020-12-12 07:43 UTC, 1Jo1 commented
@normanmaurer when benchmarking i noticed that the io workers are not destroyed(however ring fd are destroyed) this leads to the fact that i literally have to restart the vm to get rid of the worker queue because i have no memory...
let's see, I'll try other kernel version :)

2020-12-12 07:48 UTC, 1Jo1 commented
this PR is not related to this issue

2020-12-12 08:23 UTC, normanmaurer commented
@1Jo1 I wonder if this is also the same as this one https://github.com/netty/netty-incubator-transport-io_uring/issues/14 ?

2020-12-12 11:50 UTC, 1Jo1 commented
@normanmaurer yeah probably, I'll take a look :)

2020-12-16 14:54 UTC, normanmaurer commented
@1Jo1 did you find out anything yet ?

2020-12-16 15:09 UTC, 1Jo1 commented
@normanmaurer it's really weird...still trying to reproduce the bug in C...just need some time, a high number of requests and when `Native.eventFdWrite` is executed in a the wakeup method

2020-12-20 10:45 UTC, normanmaurer commented
@1Jo1 now I guess we could try a benchmark again ?

2020-12-21 04:56 UTC, 1Jo1 commented
@normanmaurer yeah sure I'm gonna do that today :) sorry I'm kind of distracted as I'm still testing the fixed io_uring patches and I found another io_uring bug however it's not related to this PR & benchmark

2020-12-22 07:36 UTC, 1Jo1 commented
that's really strange, it seems to be that `lastRingFd` is zero in `newChild` method, but lastRingFd default is -1 @normanmaurer is reflection used to set all EventLoopGroup properties to zero?

2020-12-22 07:37 UTC, normanmaurer commented
@1Jo1 no ... we don't use reflection

2020-12-22 07:39 UTC, 1Jo1 commented
@normanmaurer ok,  maybe lastRingFd is a race condition? :)

2020-12-22 07:42 UTC, normanmaurer commented
`newChild(...)` should only be called by one thread.

2020-12-22 07:45 UTC, 1Jo1 commented
BTW I get this github actions error: `Error: servers must contain id, username and password` ? so I guess is not related this PR? as the tests run successfully on my machine

2020-12-22 07:46 UTC, normanmaurer commented
@1Jo1 please rebase... I think this should fix it.

2020-12-22 07:53 UTC, 1Jo1 commented
@normanmaurer I already rebased https://github.com/1Jo1/netty-incubator-transport-io_uring/commits/shared-wq

2020-12-22 07:57 UTC, normanmaurer commented
@1Jo1 ah wait... I did mess up the GitHub workflow. Gimme a few minutes

2020-12-22 07:58 UTC, 1Jo1 commented
no worries, take your time :)

2020-12-22 08:43 UTC, normanmaurer commented
@1Jo1 please rebase again

2020-12-23 16:42 UTC, normanmaurer commented
@1Jo1 anything to share yet ?

2020-12-23 20:30 UTC, 1Jo1 commented
my VM CPU has 4 cores

Benchmark cargo run --release -- --address "127.0.0.1:3000" --number 500 --duration 60 --length 500

DEFAULT_MAX_EVENTLOOPS_WQ: 5
the shared EventLoop uses 6% less memory because of less kernel threads

worker EventLoops: 3

500 clients, running 500 bytes, 60 sec.
Speed: 151461 request/sec, 151461 response/sec
Requests: 9087677
Responses: 9087675

worker EventLoops: 5

500 clients, running 500 bytes, 60 sec.
Speed: 166397 request/sec, 166397 response/sec
Requests: 9983852
Responses: 9983851


----------------------------------------------

without shared wq
DEFAULT_MAX_EVENTLOOPS_WQ: 1

worker EventLoops: 3
Speed: 181771 request/sec, 181770 response/sec
Requests: 10906262
Responses: 10906262


worker EventLoops: 5
cargo run --release -- --address "127.0.0.1:3000" --number 500 --duration 60 --length 500
Speed: 167598 request/sec, 167598 response/sec
Requests: 10055880
Responses: 10055880

2020-12-23 20:34 UTC, 1Jo1 commented
it depends how many CPU cores you have...I will do  benchmark tests tomorrow with a 6,8 or 12 Core VM

2020-12-24 20:36 UTC, normanmaurer requested changes

2020-12-24 20:36 UTC, normanmaurer commented on src/main/java/io/netty/incubator/channel/uring/Native.java
> +    //the number of eventLoops which are associated to one work queue
nit: `// The`

2020-12-25 05:38 UTC, 1Jo1 commented
unfortunately I'm not able to connect to my workstation at home....I'm gonna run the benchmarks end of next week

2021-01-11 08:51 UTC, normanmaurer commented
@1Jo1 any updates ?

2021-01-13 07:50 UTC, 1Jo1 commented
the benchmark are still unclear to me as more io-workers are created under load, 
I guess it's not dependent on the number of cores, maybe hard limit?
anyway digging into io-workers 

```
Benchmark cargo run --release -- --address "127.0.0.1:3000" --number 500 --duration 60 --length 500
# 6 Core VM

DEFAULT_MAX_EVENTLOOPS_WQ: 1

worker Eventloop: 3
500 clients, running 500 bytes, 60 sec.
Speed: 299178 request/sec, 299178 response/sec
Requests: 17950729
Responses: 17950727

worker EventLoops: 5
Speed: 370296 request/sec, 370296 response/sec
Requests: 22217796
Responses: 22217795

worker Eventloop: 6
Speed: 445790 request/sec, 445790 response/sec
Requests: 26747407
Responses: 26747404

------------------------------------------------------------------------------

DEFAULT_MAX_EVENTLOOPS_WQ: 5

worker EventLoops: 3
Speed: 279123 request/sec, 279123 response/sec
Requests: 16747398
Responses: 16747395

worker EventLoops: 5
Speed: 414602 request/sec, 414602 response/sec
Requests: 24876165
Responses: 24876160

worker EventLoops: 6
Speed: 505535 request/sec, 505535 response/sec
Requests: 30332156
Responses: 30332155

# 12 Core

DEFAULT_MAX_EVENTLOOPS_WQ: 1

EventLoops: 3
Speed: 411137 request/sec, 411137 response/sec
Requests: 24668253
Responses: 24668249

EventLoops: 5:
Speed: 518292 request/sec, 518292 response/sec
Requests: 31097556
Responses: 31097548

EventLoops: 6
Speed: 531681 request/sec, 531681 response/sec
Requests: 31900894
Responses: 31900886

DEFAULT_MAX_EVENTLOOPS_WQ: 5

EventLoops: 3
Speed: 391585 request/sec, 391585 response/sec
Requests: 23495105
Responses: 23495101

EventLoops: 5
Speed: 426210 request/sec, 426210 response/sec
Requests: 25572639
Responses: 25572637

EventLoops: 6
Speed: 426210 request/sec, 426210 response/sec
Requests: 25572639
Responses: 25572637
```

2021-02-01 11:35 UTC, 1Jo1 commented
@normanmaurer I did several performance tests...regarding memory usage it's really hard to measure how much memory io_uring is actually using, you can only measure the total kernel memory(as far as I know) I don't think there will a big benefit in terms of memory efficiency and performance, I came to the conclusion to close the PR for now
what do you think?

2021-02-02 18:02 UTC, normanmaurer commented
let's close it for now I guess

2021-02-02 18:02 UTC, closed without merging